POST http://localhost:5600/api/item
Content-Type: application/json

{
    "item" : "This is fiseceost",
    "priority" : "high",
    "tags" : ["social life","family"]
}


###


GET http://localhost:5600/api/items
Content-Type: application/json


###

PUT http://localhost:5600/api/item/649b1aa4a946935da2bd62b5
Content-Type: application/json

{
    "item" : "Updated"
}

###


DELETE http://localhost:5600/api/item/649b1aa4a946935da2bd62b5
Content-Type: application/json

###
PUT http://localhost:5600/api/item/done/649c7c3828ff414876774841
Content-Type: application/json

{
    "done" : true
}

###
GET  http://localhost:5600/api/items/life
Content-Type: application/json

